### ISSUE TITLE
Cannot find module 'ini'

### ISSUE THREAD

**Issue by UndefinedCpp** [ScreepsMods/screepsmod-map-tool#27]
I ran this mod on my private server launched through Steam client. I installed this mod via steam workshop, and it couldn't find module `ini` when launching.

The whole report is shown below. (Some private information omitted)
```javascript
Loading mods from "***\common\Screeps\server\mods.json"
Error loading "***\common\Screeps\server\node_modules\screepsmod-map-tool\index.js": Error: Cannot find module 'ini'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:473:25)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (***\common\Screeps\server\node_modules\screepsmod-map-tool\lib\common.js:2:13)
    at Object.<anonymous> (***\common\Screeps\server\node_modules\screepsmod-map-tool\lib\common.js:27:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
```

**Comment by BigCMac** [comment]
I have the same issue
